config/routes.rb
Rails.application.routes.draw do
  
  get 'users/index'

  devise_for :users
  get 'users', :to => 'users#index'
  match 'profile',     to: 'users#show',       via: 'get'
  # match '/users/:id',     to: 'users#show',       via: 'get'

  get 'static/index'
  get 'about', :to => 'static#about'
  get 'blog', :to => 'posts#index'

  resources :users
  resources :listings
  resources :posts
  root 'static#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/listing.rb
class Listing < ApplicationRecord
	belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	has_many :posts
	has_many :listings

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:first_name, :last_name, :username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user = current_user

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:price, :category, :equipment_type, :make, :model, :year, :hours, :condition, :tire_percentage, :serial, :stock_number, :description, :listing_address, :listing_contact, :listing_phone, :listing_email, :user_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :user_id)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
  end
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
  def show
	  @user = User.find_by_username(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ForesTree Equipment Trader</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewpoint" content="width=device-width, intial-scale=1" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
    <script src="https://use.fontawesome.com/ef8c7632d4.js"></script>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "application" %>
  </head>

  <body>
  <header>
      <!-- Top Nav Bar Begin -->
      <div class="bg-primary">
        <div class="container">
          <div class="row">
            <div class="col-lg-8 col-md-8 col-sm-6 col-xs-12 top-bar-align">
              <div class="row">
                <a href="https://www.facebook.com/forestreetrader/">
                <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2 bg-hover-fetgreen">
                  <i class="fa fa-facebook fa-lg" aria-hidden="true"></i> <span class="visible-lg-inline-block">Facebook</span>
                </div>
                </a>
                <a href="https://twitter.com/FE_Trader">
                <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2 bg-hover-fetgreen">
                  <i class="fa fa-twitter fa-lg" aria-hidden="true"></i> <span class="visible-lg-inline-block">Twitter</span>
                </div>
                </a>
                <a href="https://www.youtube.com/channel/UCZ1p_k-W6gNKhIcunkvgKEw">
                <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2 bg-hover-fetgreen">
                  <i class="fa fa-youtube fa-lg" aria-hidden="true"></i> <span class="visible-lg-inline-block">Youtube</span>
                </div>
                </a>
                <a href="https://plus.google.com/+ForesTreeEquipmentTraderMontgomery/">
                <div class="col-lg-2 col-md-3 col-sm-3 col-xs-3 bg-hover-fetgreen">
                  <i class="fa fa-google-plus fa-lg" aria-hidden="true"></i> <span class="visible-lg-inline-block">Google+</span>
                </div>
                </a>
                <a href="http://www.forestreetrader.com/fet-newsletter/">
                <div class="col-lg-2 col-md-3 col-sm-3 col-xs-3 bg-hover-fetgreen">
                  <i class="fa fa-envelope fa-lg" aria-hidden="true"></i> <span class="visible-lg-inline-block">Newsletter</span>
                </div>
                </a>
              </div>
            </div>
            <a href="http://www.southernloggintimesmagazine.com">
            <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
              <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 top-bar-align">
                  <h4 class="text-right">In Partnership With </h4>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                  <%= link_to image_tag("slt-logo.png", alt: "ForesTree Equipment Trader", width: '165px') %>
                </div>
              </div>
            </div>
            </a>
          </div>
        </div>
      </div>
      <!-- Top Nav Bar End -->

      <!-- Main Nav Bar Begin -->
      <div class="container">
        <div class="row">
          <nav class="navbar navbar-light bg-faded main-nav">
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
              <ul class="nav navbar-nav navbar-left">
                <li>
                  <a class="navbar-brand fet-logo" href="#">
                    <%= link_to image_tag("fet-logo.png", alt: "ForesTree Equipment Trader"),
				  		          {:class => 'websiteLogo'} %>
                  </a>
                </li>
              </ul>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
              <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                  <ul class="nav navbar-nav navbar-right main-nav-links">
                    <li><%= link_to "Home", root_path%></li>
                    <li><%= link_to "About", about_path%></li>
                    <li><%= link_to "Blog", blog_path%></li>
                    <li><a href="#">Media Center</a></li>
                    <li><a href="#">Contact</a></li>
                    <li><a href="#">Login</a></li>
                  </ul>
                </div>
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                  <ul class="nav navbar-nav navbar-right">
                    <li><a class="bg-fetgreen" href="#">Create Listing</a></li>
                    <li><a class="bg-fetgreen" href="#">Browse Listings</a></li>
                    <li><a class="bg-fetorange" href="#">Auction</a></li>
                  </ul>
                </div>
              </div>

            </div>
          </nav>

        </div>
      </div>
      <!-- Main Nav Bar End -->
    </header>
    <body>
      <div class="container">
        <div class="row">
          <div class="col-lg-12 col-md-12 col-sm-12 col-xs">
            <!-- <p class="notice"><%= notice %></p>
            <p class="alert"><%= alert %></p> -->
            <%= yield %>
          </div>
        </div>
      </div>
    </body>
    
          

    <footer >
      <div class="fluid-container bg-primary footwidgets">
        <div class="container">
          <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
              <h2>About</h2>
              <p>
                Welcome to ForesTree Equipment Trader, the premier platform for buying, selling and trading previously owned forestry equipment, and much more. Thank you for your interest in FET!
              </p>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
              <h2>Search</h2>
              <input type="text" placeholder="Search..." />
              <button class="btn btn-fetorange" type="submit">Search</button>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
              <h2>Partners</h2>
              <p><a href="http://southernloggintimes.com/">Southern Loggin' Times</a></p>
              <p><a href="http://timberharvesting.com/">Timber Harvesting</a></p>
              <p><a href="http://hattonbrown.com/">Hatton-Brown Publishers, Inc.</a></p>
              <p><a href="http://jmwood.com/">J.M. Wood Auction Company</a></p>

            </div>
            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2">
              <%= link_to image_tag("fet-sawblade.png", alt: "ForesTree Equipment Trader", width: '175px') %>
            </div>
          </div>
        </div>
      </div>

      <div class="fluid-container bg-footerblack copyright">
        <div class="container">
          <div class="row">
            <div class="col-lg-7 col-md-6 col-sm-6 col-xs-6">
              <p>Copyright 2017 @ ForesTree Equipment Trader | Design & Development by <a href="http://www.hattonbrown.com/">HB Media</a></p>
            </div>
            <div class="col-lg-5 col-md-6 col-sm-6 col-xs-6 text-right footer-icons">
              <a href="https://www.facebook.com/forestreetrader/"><i class="fa fa-facebook" aria-hidden="true"></i></a>
              <a href="https://twitter.com/FE_Trader"><i class="fa fa-twitter" aria-hidden="true"></i></a>
              <a href="https://www.youtube.com/channel/UCZ1p_k-W6gNKhIcunkvgKEw"><i class="fa fa-youtube" aria-hidden="true"></i></a>
              <a href="https://plus.google.com/+ForesTreeEquipmentTraderMontgomery/"><i class="fa fa-google-plus" aria-hidden="true"></i></a>
            </div>
          </div>
        </div>
      </div>

      </div>
    </footer>
  </body>
</html>

app/views/listings/_form.html.erb
<%= form_with(model: listing, local: true) do |form| %>
<% if listing.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

    <ul>
    <% listing.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
  <%= form.number_field :price, id: :listing_price, placeholder: "Price" %>
</div>
<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
  <%= form.text_field :category, id: :listing_category, placeholder: "Category" %>
</div>
<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
  <%= form.text_field :equipment_type, id: :listing_equipment_type, placeholder: "Equipment Type" %>
</div>
<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
  <%= form.text_field :make, id: :listing_make, placeholder: "Make" %>
</div>
<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
  <%= form.text_field :model, id: :listing_model, placeholder: "Model" %>
</div>
<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
  <%= form.number_field :year, id: :listing_year, placeholder: "Year" %>
</div>
<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
  <%= form.number_field :hours, id: :listing_hours, placeholder: "Hours" %>
</div>
<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
  <%= form.text_field :condition, id: :listing_condition, placeholder: "Condition" %>
</div>
<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
  <%= form.number_field :tire_percentage, id: :listing_tire_percentage, placeholder: "Tire Percentage" %>
</div>
<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
  <%= form.text_field :serial, id: :listing_serial, placeholder: "Serial Number" %>
</div>
<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
  <%= form.text_field :stock_number, id: :listing_stock_number, placeholder: "Stock Number" %>
</div>
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
  <%= form.text_area :description, id: :listing_description, placeholder: "Description", width: "100%" %>
</div>
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
  <%= form.text_field :listing_address, id: :listing_listing_address, placeholder: "Listing Address" %>
</div>
<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
  <%= form.text_field :listing_contact, id: :listing_listing_contact, placeholder: "Listing Contact" %>
</div>
<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
  <%= form.number_field :listing_phone, id: :listing_listing_phone, placeholder: "Listing Phone" %>
</div>
<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
  <%= form.text_field :listing_email, id: :listing_listing_email, placeholder: "Listing Email" %>
</div>
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 actions">
  <%= form.submit %>
</div>
      
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listings</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Price</th>
      <th>Category</th>
      <th>Type</th>
      <th>Make</th>
      <th>Model</th>
      <th>Year</th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= listing.user_id %></td>
        <td><%= listing.price %></td>
        <td><%= listing.category %></td>
        <td><%= listing.equipment_type %></td>
        <td><%= listing.make %></td>
        <td><%= listing.model %></td>
        <td><%= listing.year %></td>
        
        <td><%= link_to 'Show', listing %></td>
        <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
        <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Listing', new_listing_path %>

<br>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Price:</strong>
  <%= @listing.price %>
</p>

<p>
  <strong>Category:</strong>
  <%= @listing.category %>
</p>

<p>
  <strong>Type:</strong>
  <%= @listing.equipment_type %>
</p>

<p>
  <strong>Make:</strong>
  <%= @listing.make %>
</p>

<p>
  <strong>Model:</strong>
  <%= @listing.model %>
</p>

<p>
  <strong>Year:</strong>
  <%= @listing.year %>
</p>

<p>
  <strong>Hours:</strong>
  <%= @listing.hours %>
</p>

<p>
  <strong>Condition:</strong>
  <%= @listing.condition %>
</p>

<p>
  <strong>Tire percentage:</strong>
  <%= @listing.tire_percentage %>
</p>

<p>
  <strong>Serial:</strong>
  <%= @listing.serial %>
</p>

<p>
  <strong>Stock number:</strong>
  <%= @listing.stock_number %>
</p>

<p>
  <strong>Description:</strong>
  <%= @listing.description %>
</p>

<p>
  <strong>Listing address:</strong>
  <%= @listing.listing_address %>
</p>

<p>
  <strong>Listing contact:</strong>
  <%= @listing.listing_contact %>
</p>

<p>
  <strong>Listing phone:</strong>
  <%= @listing.listing_phone %>
</p>

<p>
  <strong>Listing email:</strong>
  <%= @listing.listing_email %>
</p>

<%= link_to 'Edit', edit_listing_path(@listing) %> |
<%= link_to 'Back', listings_path %>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :post_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blog</h1>

<div class="col-lg-8 col-md-8 col-sm-8 col-xs-8">
  <%= link_to 'New Post', new_post_path %>

  <% @posts.each do |post| %>
  <h2><%= post.title %></h2>
  <h4><%= link_to 'Show', post %> | <%= link_to 'Edit', edit_post_path(post) %> | <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></h4>
  <p><%= post.body %></p>
  <% end %>
</div>


<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
  <a class="twitter-timeline" data-height="800" href="https://twitter.com/FE_Trader">Tweets by FE_Trader</a>
  <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
			<h3>List of Users</h3>
			<table>
				<tr>
					<th>First Name</th>
					<th>Last Name</th>
					<th>Email</th>
					<th>Username</th>
					<th>ID</th>
				</tr>
				<tr>
					<% @users = User.all %>
					<% @users.each do |user| %>
					<td><%= user.first_name %></td>
					<td><%= user.last_name %></td>
					<td><%= user.email %></td>
					<td><%= user.username %></td>
					<td><%= user.id %></td>
					<% end %>
				</tr>
			</table>
			
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
			<h1>Hi <%= current_user.first_name %>!</h1>
			<p><%= link_to 'Edit Profile', edit_user_registration_path(current_user) %></p>
			<p><%= link_to 'View Profile', user_path(current_user) %></p>
		</div>
	</div>
</div>